//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemProducts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public int IDProducto { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public int Stock { get; set; }
        public string Imagen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int IDCategoria { get; set; }
    
        public virtual CATEGORIAS_PRODUCTOS CATEGORIAS_PRODUCTOS { get; set; }
    }
}
